"""
Catalog loader for the Cisco ISE MCP server.

Loads the three JSON catalogs that drive the tool surfaces (generated by
``scripts/refresh_catalog.py``) once, validates their shape, and exposes
read-only accessors.  Keeping the data in versioned JSON — rather than
hand-maintained Python dicts — means the surfaces can be regenerated from the
authoritative sources (the ERS spec and Cisco DevNet) and diffed for drift.

Catalogs:
  * ers_resources.json        — ERS resources: key -> {path, label, ops, ...}
  * dataconnect_views.json    — DC views:     key -> {view, description, columns, time_col, internal}
  * openapi_endpoints.json    — Open API:     list of {tool, method, path, params, body, ...}
  * monitoring_endpoints.json — Monitoring:   list of {tool, method, path, params, body, ...}
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_CATALOG_DIR = Path(__file__).resolve().parent

_ERS_FILE = "ers_resources.json"
_DC_FILE = "dataconnect_views.json"
_OPENAPI_FILE = "openapi_endpoints.json"
_MONITORING_FILE = "monitoring_endpoints.json"
_META_FILE = "_meta.json"


def _load(filename: str):
    path = _CATALOG_DIR / filename
    if not path.is_file():
        raise FileNotFoundError(
            f"Catalog '{filename}' is missing from {_CATALOG_DIR}. "
            f"Regenerate it with:  uv run python scripts/refresh_catalog.py"
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # pragma: no cover - corrupt cache
        raise ValueError(f"Catalog '{filename}' is not valid JSON: {exc}") from exc


def missing_catalogs() -> list[str]:
    """Return the catalog files that are absent (drives the 'run refresh' prompt)."""
    return [f for f in (_ERS_FILE, _OPENAPI_FILE, _MONITORING_FILE, _DC_FILE)
            if not (_CATALOG_DIR / f).is_file()]


@lru_cache(maxsize=1)
def get_ers_resources() -> dict:
    """ERS resources keyed by resource name (e.g. 'endpoint', 'sgt')."""
    data = _load(_ERS_FILE)
    if not isinstance(data, dict) or not data:
        raise ValueError(f"{_ERS_FILE} must be a non-empty object.")
    return data


@lru_cache(maxsize=1)
def get_dc_views(include_internal: bool = False) -> dict:
    """Data Connect views keyed by lowercase view name. Internal views excluded by default."""
    data = _load(_DC_FILE)
    if not isinstance(data, dict) or not data:
        raise ValueError(f"{_DC_FILE} must be a non-empty object.")
    if include_internal:
        return data
    return {k: v for k, v in data.items() if not v.get("internal")}


@lru_cache(maxsize=1)
def get_openapi_endpoints() -> list:
    """Open API endpoints as a list of {tool, method, path, params, body, ...}."""
    data = _load(_OPENAPI_FILE)
    if not isinstance(data, list) or not data:
        raise ValueError(f"{_OPENAPI_FILE} must be a non-empty array.")
    return data


@lru_cache(maxsize=1)
def get_openapi_index() -> dict:
    """Open API endpoints keyed by tool name for O(1) dispatch lookup."""
    return {e["tool"]: e for e in get_openapi_endpoints()}


@lru_cache(maxsize=1)
def get_monitoring_endpoints() -> list:
    """Monitoring (MnT) endpoints as a list of {tool, method, path, params, body, ...}.

    Returns ``[]`` when the catalog file is absent (e.g. an older cache predating the
    Monitoring surface) so the server never fails to start over a missing file.
    """
    path = _CATALOG_DIR / _MONITORING_FILE
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # pragma: no cover - corrupt cache
        raise ValueError(f"Catalog '{_MONITORING_FILE}' is not valid JSON: {exc}") from exc
    if not isinstance(data, list):
        raise ValueError(f"{_MONITORING_FILE} must be an array.")
    return data


@lru_cache(maxsize=1)
def get_monitoring_index() -> dict:
    """Monitoring endpoints keyed by tool name for O(1) dispatch lookup."""
    return {e["tool"]: e for e in get_monitoring_endpoints()}


@lru_cache(maxsize=1)
def get_meta() -> dict:
    """Catalog provenance: source URLs, ISE version, generation time, checksums."""
    try:
        return _load(_META_FILE)
    except FileNotFoundError:
        return {}


# ---------------------------------------------------------------------------
# Fact vs dimension classification (curated — deliberately NOT in the JSON)
#
# ``scripts/refresh_catalog.py`` regenerates dataconnect_views.json by scraping
# Cisco DevNet, which has no fact/dimension notion — a curated field added to the
# JSON would be silently wiped on the next refresh. Keeping the list here means
# it survives refreshes; ``unknown_fact_views()`` guards it against rot.
#
# "Fact" = a large, high-volume event/time-series view (millions to hundreds of
# millions of rows) whose unbounded scan or join is what threatens the ISE
# Monitoring node. Everything else is a dimension: small config/lookup views
# (``network_devices`` 6 cols, ``security_groups`` 5, ``failure_code_cause`` 2)
# that are cheap to join and are exempt from the raw-SQL cost guards.
#
# NOTE: ``time_col`` is NOT a usable classifier — ``endpoint_identity_groups``,
# ``network_device_groups``, ``policy_sets`` and ``user_identity_groups`` all
# carry CREATE_TIME but are 6-7 column config tables.
# ---------------------------------------------------------------------------
_FACT_VIEWS: frozenset = frozenset({
    "radius_authentications", "radius_authentications_week", "radius_authentication_summary",
    "radius_accounting", "radius_accounting_week", "radius_errors_view",
    "tacacs_authentication", "tacacs_authentication_last_two_days",
    "tacacs_authentication_summary", "tacacs_authorization",
    "tacacs_authorization_last_two_days", "tacacs_accounting",
    "tacacs_accounting_last_two_days", "tacacs_command_accounting",
    "posture_assessment_by_condition", "posture_assessment_by_endpoint",
    "endpoints_data", "change_configuration_audit",
    "guest_accounting", "guest_devicelogin_audit", "primary_guest",
    "aup_acceptance_status", "profiled_endpoints_summary",
    "coa_events", "threat_events",
    "administrator_logins", "sponsor_login_and_audit",
    "system_diagnostics_view", "aaa_diagnostics_view",
    "key_performance_metrics", "system_summary",
    "openapi_operations", "misconfigured_nas_view", "misconfigured_supplicants_view",
    "user_password_changes", "vulnerability_assessment_failures",
    "registered_endpoints", "adaptive_network_control", "endpoint_purge_view",
})


@lru_cache(maxsize=1)
def get_fact_view_names() -> frozenset:
    """UPPER-CASED database view names classified as high-volume fact views.

    Returned in the same form ``validate_raw_select`` extracts FROM/JOIN targets,
    so membership can be tested directly.
    """
    views = get_dc_views(include_internal=True)
    names = set()
    for key in _FACT_VIEWS:
        info = views.get(key)
        # Fall back to the key when the catalog lacks the entry, so an out-of-date
        # cache still classifies the view as a fact (fail safe, not fail open).
        names.add(str(info["view"]).upper() if info else key.upper())
    return frozenset(names)


def unknown_fact_views() -> list[str]:
    """Curated fact-view keys that no longer exist in the catalog (rot guard)."""
    views = get_dc_views(include_internal=True)
    return sorted(k for k in _FACT_VIEWS if k not in views)


__all__ = [
    "get_ers_resources",
    "get_dc_views",
    "get_openapi_endpoints",
    "get_openapi_index",
    "get_monitoring_endpoints",
    "get_monitoring_index",
    "get_meta",
    "get_fact_view_names",
    "unknown_fact_views",
    "missing_catalogs",
]
