"""
Catalog loader for the Cisco ISE MCP server.

Loads the three JSON catalogs that drive the tool surfaces (generated by
``scripts/refresh_catalog.py``) once, validates their shape, and exposes
read-only accessors.  Keeping the data in versioned JSON — rather than
hand-maintained Python dicts — means the surfaces can be regenerated from the
authoritative sources (the ERS spec and Cisco DevNet) and diffed for drift.

Catalogs:
  * ers_resources.json        — ERS resources: key -> {path, label, ops, ...}
  * dataconnect_views.json    — DC views:     key -> {view, description, columns, time_col, internal}
  * openapi_endpoints.json    — Open API:     list of {tool, method, path, params, body, ...}
  * monitoring_endpoints.json — Monitoring:   list of {tool, method, path, params, body, ...}
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path

_CATALOG_DIR = Path(__file__).resolve().parent

_ERS_FILE = "ers_resources.json"
_DC_FILE = "dataconnect_views.json"
_OPENAPI_FILE = "openapi_endpoints.json"
_MONITORING_FILE = "monitoring_endpoints.json"
_META_FILE = "_meta.json"


def _load(filename: str):
    path = _CATALOG_DIR / filename
    if not path.is_file():
        raise FileNotFoundError(
            f"Catalog '{filename}' is missing from {_CATALOG_DIR}. "
            f"Regenerate it with:  uv run python scripts/refresh_catalog.py"
        )
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # pragma: no cover - corrupt cache
        raise ValueError(f"Catalog '{filename}' is not valid JSON: {exc}") from exc


def missing_catalogs() -> list[str]:
    """Return the catalog files that are absent (drives the 'run refresh' prompt)."""
    return [f for f in (_ERS_FILE, _OPENAPI_FILE, _MONITORING_FILE, _DC_FILE)
            if not (_CATALOG_DIR / f).is_file()]


@lru_cache(maxsize=1)
def get_ers_resources() -> dict:
    """ERS resources keyed by resource name (e.g. 'endpoint', 'sgt')."""
    data = _load(_ERS_FILE)
    if not isinstance(data, dict) or not data:
        raise ValueError(f"{_ERS_FILE} must be a non-empty object.")
    return data


@lru_cache(maxsize=1)
def get_dc_views(include_internal: bool = False) -> dict:
    """Data Connect views keyed by lowercase view name. Internal views excluded by default."""
    data = _load(_DC_FILE)
    if not isinstance(data, dict) or not data:
        raise ValueError(f"{_DC_FILE} must be a non-empty object.")
    if include_internal:
        return data
    return {k: v for k, v in data.items() if not v.get("internal")}


@lru_cache(maxsize=1)
def get_openapi_endpoints() -> list:
    """Open API endpoints as a list of {tool, method, path, params, body, ...}."""
    data = _load(_OPENAPI_FILE)
    if not isinstance(data, list) or not data:
        raise ValueError(f"{_OPENAPI_FILE} must be a non-empty array.")
    return data


@lru_cache(maxsize=1)
def get_openapi_index() -> dict:
    """Open API endpoints keyed by tool name for O(1) dispatch lookup."""
    return {e["tool"]: e for e in get_openapi_endpoints()}


@lru_cache(maxsize=1)
def get_monitoring_endpoints() -> list:
    """Monitoring (MnT) endpoints as a list of {tool, method, path, params, body, ...}.

    Returns ``[]`` when the catalog file is absent (e.g. an older cache predating the
    Monitoring surface) so the server never fails to start over a missing file.
    """
    path = _CATALOG_DIR / _MONITORING_FILE
    if not path.is_file():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # pragma: no cover - corrupt cache
        raise ValueError(f"Catalog '{_MONITORING_FILE}' is not valid JSON: {exc}") from exc
    if not isinstance(data, list):
        raise ValueError(f"{_MONITORING_FILE} must be an array.")
    return data


@lru_cache(maxsize=1)
def get_monitoring_index() -> dict:
    """Monitoring endpoints keyed by tool name for O(1) dispatch lookup."""
    return {e["tool"]: e for e in get_monitoring_endpoints()}


@lru_cache(maxsize=1)
def get_meta() -> dict:
    """Catalog provenance: source URLs, ISE version, generation time, checksums."""
    try:
        return _load(_META_FILE)
    except FileNotFoundError:
        return {}


__all__ = [
    "get_ers_resources",
    "get_dc_views",
    "get_openapi_endpoints",
    "get_openapi_index",
    "get_monitoring_endpoints",
    "get_monitoring_index",
    "get_meta",
    "missing_catalogs",
]
